const CONTENT: Record<string, string> = {
  /* ── Hero ── */
  "home.hero.badge":      "Plataforma White-Label para Academias Online",
  "home.hero.title1":     "Tu Academia.",
  "home.hero.title2":     "Tu Marca.",
  "home.hero.subtitle":   "AulaOS es la plataforma LMS que te permite lanzar tu academia online con tu identidad corporativa en menos de 72 horas. Sin tecnicismos, sin costes ocultos.",
  "home.hero.cta.primary":   "Ver planes y precios",
  "home.hero.cta.secondary": "Solicitar demo en vivo",
  "home.hero.proof":      "Más de 50 academias activas · Soporte en español · Sin permanencia",

  /* ── Problema ── */
  "home.problema.label":  "El problema del mercado",
  "home.problema.title":  "Crear tu academia online no debería ser esto difícil",
  "home.problema.sub":    "La mayoría de emprendedores del conocimiento pierden meses y miles de euros antes de tener algo funcional.",
  "home.problema.p0.title":  "Meses de desarrollo",
  "home.problema.p0.body":   "Contratar un desarrollador, esperar, pagar por adelantado… y aún así el resultado no es lo que esperabas.",
  "home.problema.p1.title":  "Plataformas genéricas",
  "home.problema.p1.body":   "Teachable, Thinkific, Kajabi… perfectas para USA. Caras, en inglés, sin personalización real de marca.",
  "home.problema.p2.title":  "Tu marca, diluida",
  "home.problema.p2.body":   "Cuando tus alumnos entran al área privada, ven la marca de la plataforma, no la tuya. Eso rompe la confianza.",
  "home.problema.p3.title":  "Soporte inexistente",
  "home.problema.p3.body":   "Un ticket de soporte, una FAQ en inglés, y buena suerte. Sin alguien que te entienda y te ayude en español.",

  /* ── Solución ── */
  "home.solucion.label":  "La solución AulaOS",
  "home.solucion.title":  "Todo lo que necesitas para lanzar tu academia, listo en 72 horas",
  "home.solucion.sub":    "Una plataforma completa, con tu branding, tu dominio y tus colores. Gestionada por nosotros o en tus manos.",
  "home.solucion.f0.title":  "Editor visual sin código",
  "home.solucion.f0.body":   "Cambia textos, imágenes, colores y estructura desde un editor lateral. Sin tocar una línea de código.",
  "home.solucion.f1.title":  "Área privada para alumnos",
  "home.solucion.f1.body":   "Contenido por módulos y semanas, progreso individual, diario personal, multimedia y comunidad.",
  "home.solucion.f2.title":  "Pagos integrados",
  "home.solucion.f2.body":   "Stripe nativo con planes mensuales o de pago único. Tus alumnos pagan directamente a tu cuenta.",
  "home.solucion.f3.title":  "Tu dominio, tu marca",
  "home.solucion.f3.body":   "Desplegamos en tu dominio personalizado. Tus alumnos nunca ven ninguna referencia a AulaOS.",
  "home.solucion.f4.title":  "Soporte en español",
  "home.solucion.f4.body":   "Equipo humano en España. Respondemosen menos de 24h por WhatsApp, email y videollamada.",
  "home.solucion.f5.title":  "SEO y rendimiento",
  "home.solucion.f5.body":   "Páginas estáticas ultra-rápidas con Vite. Puntuación 95+ en PageSpeed. Optimizadas para posicionamiento.",

  /* ── Caso Real: FI Academy ── */
  "home.caso.label":      "Caso real de uso",
  "home.caso.badge":      "Academia en producción",
  "home.caso.name":       "Frecuencia Integral Academy",
  "home.caso.desc":       "Academia de bienestar y desarrollo personal con el Método TCT. Lanzada con AulaOS en menos de 72 horas, con área privada completa, planes de suscripción y editor de contenido en vivo.",
  "home.caso.stat0.value": "48",
  "home.caso.stat0.label": "Semanas de contenido",
  "home.caso.stat1.value": "3",
  "home.caso.stat1.label": "Planes de acceso",
  "home.caso.stat2.value": "72h",
  "home.caso.stat2.label": "Tiempo de lanzamiento",
  "home.caso.cta":        "Ver Frecuencia Integral →",

  /* ── Experiencia del alumno ── */
  "home.alumno.label":    "Experiencia del alumno",
  "home.alumno.title":    "Una experiencia premium que tus alumnos van a amar",
  "home.alumno.sub":      "Diseñada pensando en la retención y el progreso real. Sin distracciones, sin fricciones.",
  "home.alumno.e0.title": "Área privada elegante",
  "home.alumno.e0.body":  "Dashboard personalizado con progreso visual, accesos rápidos y bienvenida con el nombre del alumno.",
  "home.alumno.e0.icon":  "🎓",
  "home.alumno.e1.title": "Contenido estructurado",
  "home.alumno.e1.body":  "Módulos, semanas o lecciones. Con bloqueo progresivo o acceso libre. Tú decides la estructura.",
  "home.alumno.e1.icon":  "📚",
  "home.alumno.e2.title": "Multimedia y recursos",
  "home.alumno.e2.body":  "Vídeos, audios, PDFs, guías y materiales descargables organizados por módulo.",
  "home.alumno.e2.icon":  "🎵",
  "home.alumno.e3.title": "Comunidad y diario",
  "home.alumno.e3.body":  "Foro de comunidad integrado y diario personal para que el alumno registre su transformación.",
  "home.alumno.e3.icon":  "✍️",

  /* ── White Label ── */
  "home.wl.label":        "White Label total",
  "home.wl.title":        "100% tu marca. 0% AulaOS visible.",
  "home.wl.sub":          "Tus alumnos solo ven tu academia. Tu logo, tus colores, tu dominio, tu experiencia de marca completa.",
  "home.wl.i0":           "Tu logo en header y favicon",
  "home.wl.i1":           "Tu paleta de colores exacta",
  "home.wl.i2":           "Tu dominio personalizado (academia.tudominio.com)",
  "home.wl.i3":           "Emails transaccionales con tu nombre",
  "home.wl.i4":           "Sin menciones a AulaOS en ningún lado",
  "home.wl.i5":           "Panel de control con tu nombre",

  /* ── Cómo funciona ── */
  "home.como.label":      "El proceso",
  "home.como.title":      "De cero a academia en 72 horas",
  "home.como.s0.num":     "01",
  "home.como.s0.title":   "Briefing de marca",
  "home.como.s0.body":    "Nos mandas tu logo, colores, estructura de curso y contenido. 30 minutos de llamada.",
  "home.como.s1.num":     "02",
  "home.como.s1.title":   "Configuración y despliegue",
  "home.como.s1.body":    "Configuramos tu plataforma, integramos Stripe y desplegamos en tu dominio. 48 horas.",
  "home.como.s2.num":     "03",
  "home.como.s2.title":   "Revisión y ajustes",
  "home.como.s2.body":    "Revisión conjunta por videollamada. Ajustes finos hasta que quede perfecto.",
  "home.como.s3.num":     "04",
  "home.como.s3.title":   "Lanzamiento y soporte",
  "home.como.s3.body":    "Tu academia live. Soporte continuo incluido en el plan mensual.",

  /* ── Precios ── */
  "home.precios.label":   "Planes y precios",
  "home.precios.title":   "Sin sorpresas. Sin letra pequeña.",
  "home.precios.sub":     "Elige la opción que mejor se adapta a tu proyecto.",

  "home.precio.gestionado.name":   "Plataforma Gestionada",
  "home.precio.gestionado.price":  "€147",
  "home.precio.gestionado.period": "/mes",
  "home.precio.gestionado.desc":   "Para creadores que quieren centrarse en su contenido. Nosotros nos encargamos de todo lo técnico.",
  "home.precio.gestionado.cta":    "Empezar ahora",
  "home.precio.gestionado.badge":  "Más popular",

  "home.precio.template.name":     "Template Tu Academia",
  "home.precio.template.price":    "€597",
  "home.precio.template.period":   "pago único",
  "home.precio.template.desc":     "Para equipos técnicos que prefieren el control total. Código completo, despliega donde quieras.",
  "home.precio.template.cta":      "Comprar template",

  /* ── FAQ ── */
  "home.faq.label":       "Preguntas frecuentes",
  "home.faq.title":       "Resolvemos tus dudas",
  "home.faq.q0":          "¿Cuánto tiempo se tarda en tener la academia lista?",
  "home.faq.a0":          "Para el plan Gestionado, el proceso completo de briefing, configuración y despliegue tarda entre 48 y 72 horas desde que recibimostu contenido y materiales de marca.",
  "home.faq.q1":          "¿Mis alumnos verán la marca de AulaOS?",
  "home.faq.a1":          "No, en absoluto. La plataforma es 100% white-label. Tu dominio, tu logo, tus colores. Ni una mención a AulaOS en ninguna parte de la experiencia del alumno.",
  "home.faq.q2":          "¿Puedo migrar mi contenido existente?",
  "home.faq.a2":          "Sí. Si ya tienes contenido en Teachable, Kajabi, Notion o cualquier otro formato, te ayudamos a migrarlo durante el proceso de configuración.",
  "home.faq.q3":          "¿Cómo funcionan los pagos de mis alumnos?",
  "home.faq.a3":          "Integramos Stripe directamente con tu cuenta. Los pagos van directamente a ti. Nosotros no tocamos ni un euro de tus ingresos.",
  "home.faq.q4":          "¿Qué pasa si quiero cancelar el plan mensual?",
  "home.faq.a4":          "Sin permanencia. Puedes cancelar cuando quieras con 30 días de aviso. Te entregamos todos tus datos y podemos ayudarte a migrar.",
  "home.faq.q5":          "¿Incluye soporte técnico?",
  "home.faq.a5":          "El plan Gestionado incluye soporte continuo en español por WhatsApp, email y videollamada. El Template incluye 30 días de soporte post-venta.",

  /* ── CTA Final ── */
  "home.cta.title":       "¿Listo para lanzar tu academia?",
  "home.cta.sub":         "Más de 50 academias ya confían en AulaOS. La tuya puede ser la próxima.",
  "home.cta.primary":     "Solicitar demo gratuita",
  "home.cta.secondary":   "Ver plantilla en vivo",
  "home.cta.note":        "Sin compromiso · Respuesta en menos de 24h · Soporte en español",

  /* ── Navbar / Footer ── */
  "home.nav.features":    "Características",
  "home.nav.pricing":     "Precios",
  "home.nav.demo":        "Ver demo",
  "home.nav.contact":     "Contacto",
  "home.footer.copy":     "© 2024 AulaOS · info@aulaos.com · Todos los derechos reservados",
};

export default CONTENT;
